### ISSUE TITLE
How do Logs and Traces actually get to the dashboard?

### ISSUE THREAD

**Issue by pkunze** [christophwille/OTel-de-Wille#1]
Maybe this is the wrong place to ask, but i don't get how you actually get traces and logs to appear in the dashboard? Neither the Dashboard nor your demo application seem to reference each other. Or did I miss something?

**Comment by christophwille** [comment]
https://github.com/christophwille/OTel-de-Wille/blob/983663735f45e596e386ba132d78317d61eefba0/aspnet-aspiredashboard/WebApplicationBuilderExtensions.cs#L28
https://github.com/christophwille/OTel-de-Wille/blob/983663735f45e596e386ba132d78317d61eefba0/aspnet-aspiredashboard/WebApplicationBuilderExtensions.cs#L71

These lines tell export to the default OTLP port 4317

https://github.com/christophwille/OTel-de-Wille/blob/983663735f45e596e386ba132d78317d61eefba0/aspnet-aspiredashboard/README.md?plain=1#L5

And that is why it is mapped via Docker that way.

**Comment by pkunze** [comment]
Thanks a lot! Do you know if it would be possible to add multiple resources/applications/services using the docker image?

**Comment by christophwille** [comment]
That is automatic via the OTLP protocol; otel-desktop-viewer, Jaeger, whatever can do that as well. The name comes from

https://github.com/christophwille/OTel-de-Wille/blob/983663735f45e596e386ba132d78317d61eefba0/aspnet-aspiredashboard/WebApplicationBuilderExtensions.cs#L43

**Comment by pkunze** [comment]
thanks :)
